version: "3.5"

services:
  auth_postgres:
    container_name: auth_postgres
    image: "postgres:13"
    env_file:
      - envs/auth/.env
    volumes:
      - $HOME/postgresql/auth_data:/var/lib/postgresql/auth_api_data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - cinema

  auth_redis:
    container_name: auth_redis
    image: redis:7
    env_file:
      - envs/auth/.env
    volumes:
      - $HOME/redis/data:/var/lib/redis/data
    ports:
      - "6379:6379"
    networks:
      - cinema

  auth:
    container_name: auth
    image: ghcr.io/praktikum-projects-team/auth_api:0.1.3
    env_file:
      - envs/auth/.env
    depends_on:
      - auth_redis
      - auth_postgres
    ports:
      - "8000:8000"
    networks:
      - cinema

  notification_postgres:
    container_name: notification_postgres
    image: "postgres:13"
    env_file:
      - envs/notification/.env
    volumes:
      - $HOME/postgresql/notification_data:/var/lib/postgresql/notification_api_data
    restart: always
    ports:
      - "5433:5432"
    networks:
      - cinema

  notification:
    container_name: notification
    build: .
    env_file:
      - envs/notification/.env
    depends_on:
      - notification_postgres
    networks:
      - cinema

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - notification
    ports:
      - "80:80"
    networks:
      - cinema


networks:
  cinema:
    name: cinema
