"""init

Revision ID: 9809c779453b
Revises: 
Create Date: 2023-07-31 03:06:44.824389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9809c779453b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_unsubscribeable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_unsubscribed',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'push', name='channel'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('events_scheduled',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('cron_string', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_templates',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'push', name='channel'), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('notifications_sent',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('delivery_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('scheduled_events_users',
    sa.Column('scheduled_event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_event_id'], ['events_scheduled.id'], ),
    sa.PrimaryKeyConstraint('scheduled_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_events_users')
    op.drop_table('notifications_sent')
    op.drop_table('notification_templates')
    op.drop_table('events_scheduled')
    op.drop_table('users_unsubscribed')
    op.drop_table('templates')
    op.drop_table('events')
    # ### end Alembic commands ###
