"""auto_generate_id

Revision ID: be7c13d8617c
Revises: 9809c779453b
Create Date: 2023-08-02 01:31:53.740872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7c13d8617c'
down_revision = '9809c779453b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
