"""welcome msg

Revision ID: ea21a405f588
Revises: 9809c779453b
Create Date: 2023-08-04 16:01:56.687139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea21a405f588'
down_revision = '9809c779453b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_links',
    sa.Column('short_link', sa.String(), nullable=False),
    sa.Column('original_link', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ttl', sa.DateTime(), nullable=False),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('short_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_links')
    # ### end Alembic commands ###
